<?php
function beetroot_post_types(){
	register_post_type( 'testimonials', [
		'label'  => null,
		'labels' => [
			'name'               => 'Testimonials',
			'singular_name'      => 'Testimonial',
			'add_new'            => 'Add testimonial',
			'add_new_item'       => 'Adding testimonial',
			'edit_item'          => 'Edit testimonial',
			'new_item'           => 'New testimonial',
			'view_item'          => 'Look testimonial',
			'search_items'       => 'Search testimonial',
			'not_found'          => 'Not found',
			'not_found_in_trash' => 'Not found',
			'parent_item_colon'  => '',
			'menu_name'          => 'Testimonials',
		],
		'description'         => '',
		'public'              => true,
		'show_in_menu'        => null,
		'show_in_rest'        => null,
		'rest_base'           => null,
		'menu_position'       => null,
		'menu_icon'           => 'dashicons-testimonial',
		'hierarchical'        => false,
		'supports'            => [ 'title','thumbnail', 'editor' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
	] );

	register_post_type( 'vacancies', [
		'label'  => null,
		'labels' => [
			'name'               => 'Vacancies',
			'singular_name'      => 'Vacancy',
			'add_new'            => 'Add vacancy',
			'add_new_item'       => 'Adding vacancy',
			'edit_item'          => 'Edit vacancy',
			'new_item'           => 'New vacancy',
			'view_item'          => 'Look vacancy',
			'search_items'       => 'Search vacancy',
			'not_found'          => 'Not found',
			'not_found_in_trash' => 'Not found',
			'parent_item_colon'  => '',
			'menu_name'          => 'Vacancies',
		],
		'description'         => '',
		'public'              => true,
		'show_in_menu'        => null,
		'show_in_rest'        => null,
		'rest_base'           => null,
		'menu_position'       => null,
		'menu_icon'           => 'dashicons-welcome-widgets-menus',
		'hierarchical'        => false,
		'supports'            => [ 'title','thumbnail', 'editor' ],
		'taxonomies'          => ['languages','locations','departments'],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
	] );
}
function beetroot_build_taxonomies(){
	register_taxonomy( 'locations', [ 'vacancies' ], [
		'label'                 => '',
		'labels'                => [
			'name'              => 'Locations',
			'singular_name'     => 'Location',
			'search_items'      => 'Search location',
			'all_items'         => 'All Location',
			'view_item '        => 'View Location',
			'parent_item'       => 'Parent Location',
			'parent_item_colon' => 'Parent Location:',
			'edit_item'         => 'Edit Location',
			'update_item'       => 'Update Location',
			'add_new_item'      => 'Add New Location',
			'new_item_name'     => 'New Location',
			'menu_name'         => 'Locations',
		],
		'description'           => '',
		'public'                => true,
		'hierarchical'          => true,

		'rewrite'               => true,
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	] );
	register_taxonomy( 'languages', [ 'vacancies' ], [
		'label'                 => '',
		'labels'                => [
			'name'              => 'Languages',
			'singular_name'     => 'Language',
			'search_items'      => 'Search language',
			'all_items'         => 'All language',
			'view_item '        => 'View language',
			'parent_item'       => 'Parent language',
			'parent_item_colon' => 'Parent language:',
			'edit_item'         => 'Edit language',
			'update_item'       => 'Update language',
			'add_new_item'      => 'Add New language',
			'new_item_name'     => 'New language',
			'menu_name'         => 'Languages',
		],
		'description'           => '',
		'public'                => true,
		'hierarchical'          => true,

		'rewrite'               => true,
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	] );
	register_taxonomy( 'departments', [ 'vacancies' ], [
		'label'                 => '',
		'labels'                => [
			'name'              => 'Departments',
			'singular_name'     => 'Department',
			'search_items'      => 'Search department',
			'all_items'         => 'All department',
			'view_item '        => 'View department',
			'parent_item'       => 'Parent department',
			'parent_item_colon' => 'Parent department:',
			'edit_item'         => 'Edit department',
			'update_item'       => 'Update department',
			'add_new_item'      => 'Add New department',
			'new_item_name'     => 'New department',
			'menu_name'         => 'Departments',
		],
		'description'           => '',
		'public'                => true,
		'hierarchical'          => true,

		'rewrite'               => true,
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	] );
}
